name:                chorewheel
version:             0.1.0.0
github:              "ftzm/chorewheel"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

#extra-source-files:
#- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ftzm/readme.org#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- base64-bytestring
- envparse
- monad-logger
- monad-control
- resource-pool
- servant >= 0.19
- servant-server >= 0.4.7.0
- servant-auth-server
#- servant-swagger
# - swagger2
- text
- aeson
- warp
- transformers
- mtl
- generic-lens
- cryptonite
- cookie
- time
- exceptions
- word8
- memory
- contravariant-extras
- raw-strings-qq
- tuple
#- optics
- hasql
- hasql-th
- hasql-pool
- hasql-transaction
- profunctors
- utf8-string
- containers
- vector
# For Tests
- tasty
- tasty-hunit
- tmp-postgres

ghc-options:
  - -Wall
  - -Werror
  - -Wwarn=missing-home-modules
  - -Wno-unused-do-bind
library:
  source-dirs: src

executables:
  chorewheel:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chorewheel

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
