name:                chorewheel
version:             0.1.0.0
github:              "ftzm/chorewheel"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

#extra-source-files:
#- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ftzm/readme.org#readme>

dependencies:
# - swagger2
#- optics
#- servant-swagger
- aeson
- name: base
  version: ">= 4.7 && < 5"
  mixin:
    - hiding (Prelude)
- base64-bytestring
- bytestring
- containers
- contravariant-extras
- cookie
- cryptonite
- envparse
- exceptions
- generic-lens
- hasql
- hasql-pool
- hasql-th
- hasql-transaction
- http-api-data
- http-media
- lucid2
- memory
- monad-control
- monad-logger
- mtl
- profunctors
- raw-strings-qq
- name: relude
  version: ">= 1.1.0.0"
  mixin:
    - (Relude as Prelude)
- resource-pool
- servant >= 0.19
- servant-auth-server
- servant-lucid
- servant-server >= 0.4.7.0
- text
- time
- transformers
- tuple
- utf8-string
- uuid
- vector
- wai
- warp
- word8
# For Tests
- tasty
- tasty-hunit
- tmp-postgres
- process

ghc-options:
  - -Wall
  - -Werror
  - -Wwarn=missing-home-modules
  - -Wno-unused-do-bind
  - -Wno-missing-home-modules
  - -Wno-type-defaults
  - -Wno-orphans

# will become language >= 0.35

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - LambdaCase
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - OverloadedRecordDot

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  chorewheel-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chorewheel

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
