name:                chorewheel
version:             0.1.0.0
github:              "ftzm/chorewheel"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

#extra-source-files:
#- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ftzm/readme.org#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- base64-bytestring
- envparse
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- monad-control
- resource-pool
- esqueleto
- servant
- servant-server
- servant-auth-server
- text
- aeson
- warp
- mtl
- generic-lens
- cryptonite
- cookie
- time

ghc-options:
  - -Wall
  - -Werror
  - -Wno-unused-do-bind
library:
  source-dirs: src

executables:
  chorewheel:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chorewheel
