#!/usr/bin/env expect

set timeout -1

send_user "starting\n"

trap {
  send \003
  send ":r\n"
  expect {
    Ok* { send "runApp\n" }
    Failed* { send_user "compilation error\n" }
    Interrupted* {
      send ":r\n"
      send "runApp\n"
    }
  }
} SIGINT

log_user 0
spawn cabal repl
log_user 1

expect Ok*

send_user "loading library\n"

send ":l ChoreWheel\n"

expect Ok*

# sleep 10

send_user "run app\n"

send "runApp\n"

# send_user "ctrl c\n"
#
# send \003


# sleep 500

expect never

exit